name = "Dodopack"
author = "Dudumaax"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ccb2b56afe46c43f255258c11209545d9871f91fb6ccac5afd95f57648094d7"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
