name = "Dodopack"
author = "Dudumaax"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba6e10d92d1bc15927cb5fcbcbbc495dedf11e5b3f18ab4f9701c75266929332"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
