name = "Dodopack"
author = "Dudumaax"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d668ea78d112584753fc8a24f7eb063dcc23518727481385a9468737bd67073"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
