name = "Dodopack"
author = "Dudumaax"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bf138e7f5bbedac889cae2404b7270a35a6b9d72f0e52a7f0fe412e933a056e"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
